# Generated by Django 3.0.4 on 2020-05-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='grade',
            field=models.TextField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='rollno',
            field=models.IntegerField(null=True),
        ),
    ]
